export { heroVariants } from './variants'
export { default as Hero } from './Hero.vue'
export { default as HeroContent } from './HeroContent.vue'
export { default as HeroTitle } from './HeroTitle.vue'
export { default as HeroDescription } from './HeroDescription.vue'
export { default as HeroActions } from './HeroActions.vue' 
export { default as HeroMedia } from './HeroMedia.vue' 